domain_path: /home/lsh/2025/practice/axi_fsm_v3/sw/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/lsh/tools/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
